import Head from 'next/head'
import Image from 'next/image'
import { ThemeProvider } from 'styled-components'
import { GifGrid, Header, SearchBar, SearchHistory, ResultsCallout } from '@/components'
import { GlobalStyles, theme } from '@/styles/global.styles'
import { GifContext } from '@/providers'
import { normalizeGiphyResponse } from '@/utils'
import { GIPHY_API_BASE, GIPHY_API_KEY } from '@/constants'

// TODO move?
const GiphyHead = () => (
  <Head>
    <title>GIPHY GRABBER</title>
    <meta name='description' content='Generated by create next app' />
    <meta name='viewport' content='width=device-width, initial-scale=1' />
    <link rel='icon' href='/favicon.ico' />
    <link href='https://fonts.cdnfonts.com/css/lato' rel='stylesheet' />
  </Head>
)

export default function Home({ gifs }) {
  return (
    <ThemeProvider theme={theme}>
      <GlobalStyles />
      <GiphyHead />
      <GifContext.Provider>
        <main>
          <Header />
          <SearchBar />
          <SearchHistory />
          <ResultsCallout />
          <GifGrid {...{ gifs }} />
        </main>
      </GifContext.Provider>
    </ThemeProvider>
  )
}

// TODO this fetch logic is duplicated in gifs.js...consolidate
Home.getInitialProps = async ctx => {
  if (!GIPHY_API_KEY) {
    return { gifs: [], error: { status: 401, message: 'GIPHY API Key is invalid/missing' } }
  }

  let url = `${GIPHY_API_BASE}/trending?api_key=${GIPHY_API_KEY}&limit=25&rating=g`
  if (ctx.query && Object.keys(ctx.query).length) {
    const { q, page } = req.query
    url = `${GIPHY_API_BASE}/search?api_key=${GIPHY_API_KEY}&q=${q}&offset=${
      page ?? 0
    }&limit=20&rating=g&lang=en`
  }
  const fetchResponse = await fetch(url)
  const gifs = await fetchResponse.json()
  return normalizeGiphyResponse(gifs)
}
