import Head from 'next/head'
import { ThemeProvider } from 'styled-components'
import { GifGrid, Header, SearchBar, SearchHistory, ResultsCallout } from '@/components'
import { GlobalStyles, theme } from '@/styles/global.styles'
import { GifContext } from '@/providers'
import { normalizeGiphyResponse } from '@/utils'
import { giphySearchUrl, giphyTrendingUrl } from '@/constants'

const GiphyHead = () => (
  <Head>
    <title>GIPHY GRABBER</title>
    <meta name='description' content='Generated by create next app' />
    <meta name='viewport' content='width=device-width, initial-scale=1' />
    <link rel='icon' href='/favicon.ico' />
    <link href='https://fonts.cdnfonts.com/css/lato' rel='stylesheet' />
  </Head>
)

export default function Home({ gifs }) {
  return (
    <ThemeProvider theme={theme}>
      <GlobalStyles />
      <GiphyHead />
      <GifContext.Provider initialState={gifs}>
        <main>
          <Header />
          <SearchBar />
          <SearchHistory />
          <ResultsCallout />
          <GifGrid />
        </main>
      </GifContext.Provider>
    </ThemeProvider>
  )
}

Home.getInitialProps = async ctx => {
  const { q, page } = ctx.req.query ?? {}
  const fetchResponse = await fetch(q ? giphySearchUrl(q, page) : giphyTrendingUrl(page))
  const gifs = await fetchResponse.json()
  return { gifs: normalizeGiphyResponse(gifs) }
}
