import Head from 'next/head'
import Image from 'next/image'
import { ThemeProvider } from 'styled-components'
import { GifGrid, Header, SearchBar, SearchHistory, ResultsCallout } from '@/components'
import { GlobalStyles, theme } from '@/styles/global.styles'
import { GifContext } from '@/providers'
import { normalizeGiphyResponse } from '@/utils'
import { GIPHY_API_BASE, GIPHY_API_KEY } from '@/constants'

// TODO move?
const GiphyHead = () => (
  <Head>
    <title>GIPHY GRABBER</title>
    <meta name='description' content='Generated by create next app' />
    <meta name='viewport' content='width=device-width, initial-scale=1' />
    <link rel='icon' href='/favicon.ico' />
    <link href='https://fonts.cdnfonts.com/css/lato' rel='stylesheet' />
  </Head>
)

export default function Home({ gifs }) {
  return (
    <ThemeProvider theme={theme}>
      <GlobalStyles />
      <GiphyHead />
      <GifContext.Provider initialState={gifs}>
        <main>
          <Header />
          <SearchBar />
          <SearchHistory />
          <ResultsCallout />
          <GifGrid />
        </main>
      </GifContext.Provider>
    </ThemeProvider>
  )
}

Home.getInitialProps = async ctx => {
  const { q, page } = ctx.req.query ?? {}
  const trendingUrl = `${GIPHY_API_BASE}/trending?api_key=${GIPHY_API_KEY}&limit=25&rating=g`
  const searchUrl = `${GIPHY_API_BASE}/search?api_key=${GIPHY_API_KEY}&q=${q}&offset=${
    page || 1
  }&limit=20&rating=g&lang=en`
  console.log('\n****GIP****\n\n', q, page)

  const fetchResponse = await fetch(q ? trendingUrl : searchUrl)
  const gifs = await fetchResponse.json()
  return { gifs: normalizeGiphyResponse(gifs) }
}
